version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myApp

hooks:
  ApplicationStart:
    - location: ./start.sh
      timeout: 60
      runas: ubuntu
  ApplicationStop:
    - location: ./stop.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall:
    - location: ./before.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: ./validate.sh
      timeout: 60
      runas: ubuntu
