version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myApp

hooks:
  ApplicationStart:
    - location: ./codeDeployScripts/start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: ./codeDeployScripts/stop.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: ./codeDeployScripts/before.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: ./codeDeployScripts/validate.sh
      timeout: 60
      runas: root
