version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myApp

permissions:
  - object: /home/ubuntu/myApp
    pattern: "**"
    owner: root
    group: root
    mode: 755
    type:
      - file

hooks:
  ApplicationStart:
    - location: ./myApp/codeDeployScripts/start.sh
      timeout: 20
      runas: ubuntu
  ApplicationStop:
    - location: ./myApp/codeDeployScripts/stop.sh
      timeout: 20
      runas: ubuntu
  BeforeInstall:
    - location: ./myApp/codeDeployScripts/before.sh
      timeout: 20
      runas: ubuntu
  ValidateService:
    - location: ./myApp/codeDeployScripts/validate.sh
      timeout: 60
      runas: ubuntu
