version: 2.0

jobs:
  pr:
    docker:
      - image: circleci/openjdk:13-buster-node-browsers-legacy
    working_directory: ~/webapp
    steps:
      - checkout
      - run:
          name: Do a clean install and run unit tests
          command: mvn clean install

  build_deploy:
    docker:
      - image: circleci/openjdk:13-buster-node-browsers-legacy
    working_directory: ~/webapp
    steps:
      - checkout
      - run:
          name: Install AWS cli
          command: |
            python --version
            cat /etc/issue
            sudo apt-get update -y
            sudo apt-get install -y python-pip 
            sudo pip install awscli 
            sudo pip install aws-sam-cli
      - run:
          name: Configure AWS cli
          command: |
            aws --version
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set default.region ${AWS_DEFAULT_REGION}
            aws configure list
      - run:
          name: Builds the jar file for the webapp
          command: |
            mvn clean install
            pwd
            ls -al
            ls -al target/
      - run:
          name: Create a zip file to be deployed on the S3 Bucket
          command: |
            sudo chmod +x codeDeployScripts/*.sh
            mkdir codedeploy_artifact
            cd codedeploy_artifact
            ls -al
            cd ..
            pwd
            ls -al
            sudo cp appspec.yml codedeploy_artifact/
            sudo cp -r codeDeployScripts codedeploy_artifact/
            sudo cp ./target/ROOT.jar codedeploy_artifact/
            pwd
            cd codedeploy_artifact
            pwd
            ls -al
            cd ..
            pwd
            ls -al
      - run:
          name: Push the new revision of the application to S3
          command: |
            aws deploy push \
              --application-name ${CODEDEPLOY_APPLICATION_NAME} \
              --description "This is a new revision for the application" \
              --ignore-hidden-files \
              --s3-location s3://${S3_CODEDEPLOY_BUCKET}/csye6225-webapp-${CIRCLE_BUILD_NUM}.zip \
              --source ./codedeploy_artifact/
      - run:
          name: Fetch from S3 and Deploy the application to codedeploy
          command: |
            aws deploy create-deployment --application-name ${CODEDEPLOY_APPLICATION_NAME} \
              --deployment-config-name CodeDeployDefault.AllAtOnce \
              --deployment-group-name ${CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME} \
              --description "CSYE-6225 - CodeDeploy" \
              --region ${AWS_DEFAULT_REGION} \
              --s3-location bucket=${S3_CODEDEPLOY_BUCKET},key=csye6225-webapp-${CIRCLE_BUILD_NUM}.zip,bundleType=zip \
              --output json

workflows:
  version: 2
  pr_check:
    jobs:
      - pr
  build_and_deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only:
                - master
